export const profile = {
    'profileName': {
        'en': 'NAME',
        'es': 'NOMBRE',
        'pt': 'NOME'
    },
    'profileNameContent': {
        'en': 'RUBÉN ANDRÉS MENDOZA BURGOS',
        'es': 'RUBÉN ANDRÉS MENDOZA BURGOS',
        'pt': 'RUBÉN ANDRÉS MENDOZA BURGOS'
    },
    'profileLocation': {
        'en': 'LOCATION',
        'es': 'LOCALIZACIÓN',
        'pt': 'LOCALIZAÇÃO'
    },
    'profileLocationContent': {
        'en': 'QUERETARO, MEXICO',
        'es': 'QUERÉTARO, MÉXICO',
        'pt': 'QUERÉTARO, MÉXICO'
    },
    'profileNickname': {
        'en': 'PSEUDONYM',
        'es': 'PSEUDÓNIMO',
        'pt': 'PSEUDÔNIMO'
    },
    'profileNicknameContent': {
        'en': 'RAMB MEMBURG',
        'es': 'RAMB MEMBURG',
        'pt': 'RAMB MEMBURG',
    },
    'profileEducation': {
        'en': 'EDUCATION',
        'es': 'EDUCACIÓN',
        'pt': 'EDUCAÇÃO'
    },
    'profileEducationContent': {
        'en': 'AUTONOMOUS UNIVERSITY OF QUERÉTARO',
        'es': 'UNIVERSIDAD AUTÓNOMA DE QUERÉTARO',
        'pt': 'UNIVERSIDADE AUTÔNOMA DE QUERÉTARO'
    },
    'profileMoreStuff': {
        'en': 'MORE STUFF',
        'es': 'MÁS COSAS',
        'pt': 'MAIS COISAS'
    },
    'profileMoreStuffContent': {
        'en': "I'M PASSIONATE ABOUT SCIENCE AND TECHNOLOGY, I ALWAYS WANT TO LEARN NEW THINGS. I LIKE ATHLETICS AND PLAYING VIDEOGAMES. SOME PROGRAMMING LANGUAGES I LIKE AND I FEEL COMFORTABLE WITH ARE JAVASCRIPT, PYTHON, MATLAB, AND C; ALSO I'M CURRENTLY LEARNING REACT.",
        'es': "SOY APASIONADO POR LA CIENCIA Y LA TECNOLOGÍA, SIEMPRE QUIERO APRENDER COSAS NUEVAS. ME GUSTA EL ATLETISMO Y JUGAR VIDEOJUEGOS. ALGUNOS LENGUAJES DE PROGRAMACIÓN QUE ME GUSTAN Y CON LOS QUE ME SIENTO CÓMODO SON JAVASCRIPT, PYTHON, MATLAB Y C; ACTUALMENTE TAMBIÉN ESTOY APRENDIENDO REACT.",
        'pt': "SOU APAIXONADO POR CIÊNCIA E TECNOLOGIA, SEMPRE QUERO APRENDER NOVAS COISAS. GOSTO DE ATLETISMO E DE JOGAR VIDEOGAMES. ALGUMAS LINGUAGENS DE PROGRAMAÇÃO DE QUE GOSTO E COM AS QUAIS ME SENTE CONFORTÁVEL SÃO JAVASCRIPT, PYTHON, MATLAB E C; ATUALMENTE TAMBÉM ESTOU APRENDENDO O REACT."
    }
}

export const navbar = {
    'navbarProfile': {
        'en': 'PROFILE',
        'es': 'PERFIL',
        'pt': 'PERFIL'
    },
    'navbarExperience': {
        'en': 'EXPERIENCE',
        'es': 'EXPERIENCIA',
        'pt': 'EXPERIÊNCIA'
    },
    'navbarProjects': {
        'en': 'PROJECTS',
        'es': 'PROYECTOS',
        'pt': 'PROJETOS'
    },
    'navbarContact': {
        'en': 'CONTACT',
        'es': 'CONTACTO',
        'pt': 'CONTATO'
    }
}

export const experience = {
    'experienceCompany-1': {
        'en': 'PSL GROUP',
        'es': 'PSL GROUP',
        'pt': 'PSL GROUP'
    },
    'experienceDate-1': {
        'en': ' 06/21-TODAY',
        'es': ' 06/21-HOY',
        'pt': ' 06/21-HOJE'
    },
    'experienceRole-1': {
        'en': 'QUALITY ASSURANCE ANALYST',
        'es': 'ANALISTA DE GARANTÍA DE CALIDAD',
        'pt': 'ANALISTA DE GARANTIA DE QUALIDADE'
    },
    'experienceDesc-1': {
        'en': 'ENSURE QUALITY OF DIFFERENT INNER APPS (FOCUSED ON API TESTING). I MOSTLY WORK WITH JAVA, POSTMAN, POSTGRESQL, AND SNOWFLAKE.',
        'es': 'ASEGURO LA CALIDAD DE DIFERENTES APLICACIONES INTERNAS (ENFOCADAS EN PRUEBAS DE APIS). TRABAJO MAYORMENTE CON JAVA, POSTMAN, POSTGRESQL Y SNOWFLAKE.',
        'pt': 'GARANTO A QUALIDADE DOS DIFERENTES APLICATIVOS INTERNOS (COM FOCO EM TESTES APIS). EU TRABALHO MAIS COM JAVA, POSTMAN, POSTGRESQL E SNOWFLAKE.'
    },
    'experienceCompany-2': {
        'en': 'DELOITTE',
        'es': 'DELOITTE',
        'pt': 'DELOITTE'
    },
    'experienceDate-2': {
        'en': ' 02/20-06/21',
        'es': ' 02/20-06/21',
        'pt': ' 02/20-06/21'
    },
    'experienceRole-2': {
        'en': 'SYSTEMS ENGINEERING ANALYST',
        'es': 'ANALISTA DE INGENIERÍA EN SISTEMAS',
        'pt': 'ANALISTA DE ENGENHARIA DE SISTEMAS'
    },
    'experienceDesc-2': {
        'en': 'WORKED ON A PROJECT FOR A WORLDWIDE COMPANY (DISNEY), ENSURED THE QUALITY OF WEB BASED PROJECTS AND MOBILE APPS (IOS & ANDROID) AS WELL. I MOSTLY USED WEBDRIVERIO, JAVASCRIPT, SELENIUM, AND JAVA.',
        'es': 'TRABAJÉ EN UN PROYECTO PARA UNA EMPRESA MUNDIAL (DISNEY), ASEGURÉ LA CALIDAD DE PROYECTOS BASADOS EN WEB Y APLICACIONES MÓVILES (IOS Y ANDROID) TAMBIÉN. MAYORMENTE UTILIZÉ WEBDRIVERIO, JAVASCRIPT, SELENIUM Y JAVA.',
        'pt': 'TRABALHEI EM UM PROJETO PARA UMA EMPRESA MUNDIAL (DISNEY), ASSEGUREI A QUALIDADE DOS PROJETOS COM BASE EM APLICATIVOS DA WEB E MÓVEL (IOS E ANDROID) TAMBÉM. TRABALHEI PRINCIPALMENTE COM WEBDRIVERIO, JAVASCRIPT, SELENIUM E JAVA.'
    },
    'experienceCompany-3': {
        'en': 'UNAM-LAVIS',
        'es': 'UNAM-LAVIS',
        'pt': 'UNAM-LAVIS'
    },
    'experienceDate-3': {
        'en': ' 09/18-01/20',
        'es': ' 09/18-01/20',
        'pt': ' 09/18-01/20'
    },
    'experienceRole-3': {
        'en': 'DEVELOPER & RESEARCHER',
        'es': 'DESARROLLADOR E INVESTIGADOR',
        'pt': 'DESENVOLVEDOR E PESQUISADOR'
    },
    'experienceDesc-3': {
        'en': 'AS PART OF MY SOCIAL SERVICE AND VOLUNTEERING I HAD THE OPPORTUNITY TO DEVELOP 3D VISUALISATION AND IMAGE PROCESSING SOFTWARE RELATED TO NEUROSCIENCE AND BIOMECHANICS USING TECHNOLOGIES SUCH AS UNITY, MATLAB, HTML, CSS, AND JAVASCRIPT.',
        'es': 'COMO PARTE DE MI SERVICIO SOCIAL Y DE VOLUNTARIADO, TUVE LA OPORTUNIDAD DE DESARROLLAR SOFTWARE DE VISUALIZACIÓN 3D Y PROCESAMIENTO DE IMÁGENES RELACIONADO CON NEUROCIENCIA Y BIOMECÁNICA USANDO TECNOLOGÍAS COMO UNITY, MATLAB, HTML, CSS Y JAVASCRIPT.',
        'pt': 'COMO PARTE DO MEU SERVIÇO SOCIAL E VOLUNTÁRIO, TIVE A OPORTUNIDADE DE DESENVOLVER SOFTWARE DE VISUALIZAÇÃO E PROCESSAMENTO DE IMAGEM EM 3D RELACIONADO À NEUROCIÊNCIA E BIOMECÂNICA USANDO TECNOLOGIAS COMO UNITY, MATLAB, HTML, CSS E JAVASCRIPT.'
    }
}

export const projects = {
    'projectDesc-1': {
        'en': 'CHEEMS IS A PROGRAMMING LANGUAGE STILL UNDER CONSTRUCTION AND WRITTEN IN JAVASCRIPT. JUST FOR THE MEMES, IT IS A MEMELANG.',
        'es': 'CHEEMS ES UN LENGUAJE DE PROGRAMACIÓN AÚN EN CONSTRUCCIÓN Y ESCRITO EN JAVASCRIPT. SOLO PARA LOS MEMES, ES UN MEMELANG.',
        'pt': 'CHEEMS É UMA LINGUAGEM DE PROGRAMAÇÃO AINDA EM CONSTRUÇÃO E ESCRITO EM JAVASCRIPT. SOMENTE PARA MEMES, É UM MEMELANG.'
    },
    'projectDesc-2': {
        'en': 'DUOLINGO DESTROYER IS AN AUTOMATION WORK CREATED MEANT TO BEAT DUOLINGO. USING WEBDRIVERIO FRAMEWORK, WRITTEN IN TYPESCRIPT AND IMPLEMENTING THE PAGE OBJECT MODEL DESIGN PATTERN.',
        'es': 'DUOLINGO DESTROYER ES UN TRABAJO DE AUTOMATIZACIÓN CREADA PARA GANARLE A DUOLINGO. UTILIZANDO EL FRAMEWORK WEBDRIVERIO, ESCRITO EN TYPESCRIPT E IMPLEMENTANDO EL PATRÓN DE DISEÑO DEL MODELO DE OBJETO DE PÁGINA.',
        'pt': 'DUOLINGO DESTROYER É UM TRABALHO DE AUTOMAÇÃO CRIADO PARA VENCER DUOLINGO. UTILIZANDO O FRAMEWORK WEBDRIVERIO, ESCRITO EM TYPESCRIPT E IMPLEMENTADO O PADRÃO DE PROJETO DO MODELO DE OBJETO DE PÁGINA.'
    },
    'projectDesc-3': {
        'en': 'A SET OF IMAGE PROCESSING ALGORITHMS WRITTEN IN PURE JAVASCRIPT, THESE ALGORITHMS ARE MEANT TO RUN ON WEB BROWSER SINCE WEB CANVAS IS IMPLEMENTED.',
        'es': 'UN CONJUNTO DE ALGORITMOS DE PROCESAMIENTO DE IMÁGENES ESCRITOS EN JAVASCRIPT PURO, ESTOS ALGORITMOS ESTÁN PENSADOS PARA EJECUTARSE EN EL NAVEGADOR WEB PORQUE QUE SE IMPLEMENTA EL WEB CANVAS.',
        'pt': 'UM CONJUNTO DE ALGORITMOS DE PROCESSAMENTO DE IMAGEM ESCRITOS EM JAVASCRIPT PURO, ESTES ALGORITMOS DESTINAM-SE A SER EXECUTADOS NO NAVEGADOR DA WEB PORQUE A WEB CANVAS ESTÁ IMPLEMENTADA.'
    }
}

export const contact = {
    'contactMail': {
        'en': 'EMAIL',
        'es': 'CORREO',
        'pt': 'EMAIL'
    },
    'contactMailContent': {
        'en': 'HEISRAMBY[AT]GMAIL.COM',
        'es': 'HEISRAMBY[AT]GMAIL.COM',
        'pt': 'HEISRAMBY[AT]GMAIL.COM'
    },
    'contactGitHub': {
        'en': 'GITHUB',
        'es': 'GITHUB',
        'pt': 'GITHUB'
    },
    'contactGitHubContent': {
        'en': 'MEMBURG',
        'es': 'MEMBURG',
        'pt': 'MEMBURG'
    },
    'contactGitLab': {
        'en': 'GITLAB',
        'es': 'GITLAB',
        'pt': 'GITLAB'
    },
    'contactGitLabContent': {
        'en': 'MEMBURG',
        'es': 'MEMBURG',
        'pt': 'MEMBURG'
    },
    'contactLinkedIn': {
        'en': 'LINKEDIN',
        'es': 'LINKEDIN',
        'pt': 'LINKEDIN'
    },
    'contactLinkedInContent': {
        'en': 'MEMBURG',
        'es': 'MEMBURG',
        'pt': 'MEMBURG'
    },
    'contactTwitter': {
        'en': 'TWITTER',
        'es': 'TWITTER',
        'pt': 'TWITTER'
    },
    'contactTwitterContent': {
        'en': '[AT]MEMBURG',
        'es': '[AT]MEMBURG',
        'pt': '[AT]MEMBURG'
    }
}

export const multilangMonths = {
    'en': ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'],
    'es': ['ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AGO', 'SEP', 'OCT', 'NOV', 'DIC'],
    'pt': ['JAN', 'FEV', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AUG', 'SET', 'OUT', 'NOV', 'DEZ']
}