export const profile = {
    'profileName': {
        'en': 'NAME',
        'es': 'NOMBRE',
        'pt': 'NOME'
    },
    'profileNameContent': {
        'en': 'RUBÉN ANDRÉS MENDOZA BURGOS',
        'es': 'RUBÉN ANDRÉS MENDOZA BURGOS',
        'pt': 'RUBÉN ANDRÉS MENDOZA BURGOS'
    },
    'profileLocation': {
        'en': 'LOCATION',
        'es': 'LOCALIZACIÓN',
        'pt': 'LOCALIZAÇÃO'
    },
    'profileLocationContent': {
        'en': 'QUERETARO, MEXICO',
        'es': 'QUERÉTARO, MÉXICO',
        'pt': 'QUERÉTARO, MÉXICO'
    },
    'profileNickname': {
        'en': 'PSEUDONYM',
        'es': 'PSEUDÓNIMO',
        'pt': 'PSEUDÔNIMO'
    },
    'profileNicknameContent': {
        'en': 'RAMB MEMBURG',
        'es': 'RAMB MEMBURG',
        'pt': 'RAMB MEMBURG',
    },
    'profileEducation': {
        'en': 'EDUCATION',
        'es': 'EDUCACIÓN',
        'pt': 'EDUCAÇÃO'
    },
    'profileEducationContent': {
        'en': 'AUTONOMOUS UNIVERSITY OF QUERÉTARO',
        'es': 'UNIVERSIDAD AUTÓNOMA DE QUERÉTARO',
        'pt': 'UNIVERSIDADE AUTÔNOMA DE QUERÉTARO'
    },
    'profileMoreStuff': {
        'en': 'MORE STUFF',
        'es': 'MÁS COSAS',
        'pt': 'MAIS COISAS'
    },
    'profileMoreStuffContent': {
        'en': "I'M PASSIONATE ABOUT SCIENCE AND TECHNOLOGY, I ALWAYS WANT TO LEARN NEW THINGS. I LIKE ATHLETICS AND PLAYING VIDEOGAMES. SOME PROGRAMMING LANGUAGES I LIKE AND I FEEL COMFORTABLE WITH ARE JAVASCRIPT, PYTHON, MATLAB, AND C; ALSO I'M CURRENTLY LEARNING REACT.",
        'es': "SOY APASIONADO POR LA CIENCIA Y LA TECNOLOGÍA, SIEMPRE QUIERO APRENDER COSAS NUEVAS. ME GUSTA EL ATLETISMO Y JUGAR VIDEOJUEGOS. ALGUNOS LENGUAJES DE PROGRAMACIÓN QUE ME GUSTAN Y CON LOS QUE ME SIENTO CÓMODO SON JAVASCRIPT, PYTHON, MATLAB Y C; ACTUALMENTE TAMBIÉN ESTOY APRENDIENDO REACT.",
        'pt': "SOU APAIXONADO POR CIÊNCIA E TECNOLOGIA, SEMPRE QUERO APRENDER NOVAS COISAS. GOSTO DE ATLETISMO E DE JOGAR VIDEOGAMES. ALGUMAS LINGUAGENS DE PROGRAMAÇÃO DE QUE GOSTO E COM AS QUAIS ME SENTE CONFORTÁVEL SÃO JAVASCRIPT, PYTHON, MATLAB E C; ATUALMENTE TAMBÉM ESTOU APRENDENDO O REACT."
    }
}

export const navbar = {
    'navbarProfile': {
        'en': 'PROFILE',
        'es': 'PERFIL',
        'pt': 'PERFIL'
    },
    'navbarExperience': {
        'en': 'EXPERIENCE',
        'es': 'EXPERIENCIA',
        'pt': 'EXPERIÊNCIA'
    },
    'navbarProjects': {
        'en': 'PROJECTS',
        'es': 'PROYECTOS',
        'pt': 'PROJETOS'
    },
    'navbarContact': {
        'en': 'CONTACT',
        'es': 'CONTACTO',
        'pt': 'CONTATO'
    }
}

export const experience = {
    'experienceCompany-1': {
        'en': 'DELOITTE',
        'es': 'DELOITTE',
        'pt': 'DELOITTE'
    },
    'experienceDate-1': {
        'en': ' 06/20-TODAY',
        'es': ' 06/20-HOY',
        'pt': ' 06/20-HOJE'
    },
    'experienceRole-1': {
        'en': 'SYSTEMS ENGINEERING ANALYST',
        'es': 'ANALISTA DE INGENIERÍA EN SISTEMAS',
        'pt': 'ANALISTA DE ENGENHARIA DE SISTEMAS'
    },
    'experienceDesc-1': {
        'en': 'CURRENTLY WORKING FOR DISNEY; CARRYING OUT AUTOMATION AND MANUAL TESTING, GUARANTEING THE QUALITY OF A MOBILE APPLICATION, ALL THROUGH THE USE OF DIFFERENT TECHNOLOGIES SUCH AS NODEJS, APPIUM AND WEBDRIVERIO. I ALSO MADE AUTOMATION AND MANUAL TESTING FOR TWO DIFFERENT WEB APPLICATIONS, I USED TECHNOLOGIES LIKE JAVA AND SELENIUM.',
        'es': 'ACTUALMENTE TRABAJANDO PARA DISNEY; REALIZANDO AUTOMATIZACIÓN Y PRUEBAS MANUALES, GARANTIZANDO LA CALIDAD DE UNA APLICACIÓN MÓVIL, TODO ESTO MEDIANTE EL USO DE DIFERENTES TECNOLOGÍAS COMO NODEJS, APPIUM Y WEBDRIVERIO. TAMBIÉN HICE AUTOMATIZACIÓN Y PRUEBAS MANUALES PARA DOS DIFERENTES APLICACIONES WEB, UTILICÉ TECNOLOGÍAS COMO JAVA Y SELENIUM.',
        'pt': 'ATUALMENTE TRABALHANDO PARA A DISNEY; REALIZANDO AUTOMATIZAÇÃO E TESTE MANUAL, GARANTIDO A QUALIDADE DE UM APLICATIVO MÓVEL, ATRAVÉS DO USO DE DIFERENTES TECNOLOGIAS COMO NODEJS, APPIUM E WEBDRIVERIO. TAMBÉM FIZ AUTOMATIZAÇÃO E TESTE MANUAL PARA DUAS APLICAÇÕES WEB DIFERENTES, UTILIZEI TECNOLOGIAS COMO JAVA E SELENIUM.'
    },
    'experienceCompany-2': {
        'en': 'DELOITTE',
        'es': 'DELOITTE',
        'pt': 'DELOITTE'
    },
    'experienceDate-2': {
        'en': ' 02/20-06/20',
        'es': ' 02/20-06/20',
        'pt': ' 02/20-06/20'
    },
    'experienceRole-2': {
        'en': 'QUALITY ASSURANCE TRAINEE',
        'es': 'BECARIO DE ASEGURAMIENTO DE CALIDAD',
        'pt': 'BECARIO DE ASEGURAMIENTO DE CALIDAD'
    },
    'experienceDesc-2': {
        'en': 'I LEARNT AUTOMATION TESTING TOOLS SUCH AS SELENIUM AND APPIUM, ISTQB PRINCIPLES, ORAL SPEECH AND COMMUNICATION TECHNIQUES; AND DEVELOPMENT METHODOLOGIES SUCH AS WATERFALL AND SCRUM.',
        'es': 'APRENDÍ HERRAMIENTAS DE PRUEBA DE AUTOMATIZACIÓN COMO SELENIUM Y APPIUM, PRINCIPIOS ISTQB, TÉCNICAS DE HABLA ORAL Y COMUNICACIÓN; Y METODOLOGÍAS DE DESARROLLO COMO WATERFALL Y SCRUM.',
        'pt': 'APRENDI FERRAMENTAS DE TESTE DE AUTOMAÇÃO COMO SELENIUM E APPIUM, PRINCÍPIOS ISTQB, FALA ORAL E TÉCNICAS DE COMUNICAÇÃO; E METODOLOGIAS DE DESENVOLVIMENTO, COMO WATERFALL E SCRUM.'
    },
    'experienceCompany-3': {
        'en': 'UNAM-LAVIS',
        'es': 'UNAM-LAVIS',
        'pt': 'UNAM-LAVIS'
    },
    'experienceDate-3': {
        'en': ' 09/18-01/20',
        'es': ' 09/18-01/20',
        'pt': ' 09/18-01/20'
    },
    'experienceRole-3': {
        'en': 'DEVELOPER & RESEARCHER',
        'es': 'DESARROLLADOR E INVESTIGADOR',
        'pt': 'DESENVOLVEDOR E PESQUISADOR'
    },
    'experienceDesc-3': {
        'en': 'AS PART OF MY SOCIAL SERVICE AND VOLUNTEERING I HAD THE OPPORTUNITY TO DEVELOP 3D VISUALISATION AND IMAGE PROCESSING SOFTWARE RELATED TO NEUROSCIENCE AND BIOMECHANICS USING TECHNOLOGIES SUCH AS UNITY, MATLAB, HTML, CSS, AND JAVASCRIPT.',
        'es': 'COMO PARTE DE MI SERVICIO SOCIAL Y DE VOLUNTARIADO, TUVE LA OPORTUNIDAD DE DESARROLLAR SOFTWARE DE VISUALIZACIÓN 3D Y PROCESAMIENTO DE IMÁGENES RELACIONADO CON NEUROCIENCIA Y BIOMECÁNICA USANDO TECNOLOGÍAS COMO UNITY, MATLAB, HTML, CSS Y JAVASCRIPT.',
        'pt': 'COMO PARTE DO MEU SERVIÇO SOCIAL E VOLUNTÁRIO, TIVE A OPORTUNIDADE DE DESENVOLVER SOFTWARE DE VISUALIZAÇÃO E PROCESSAMENTO DE IMAGEM EM 3D RELACIONADO À NEUROCIÊNCIA E BIOMECÂNICA USANDO TECNOLOGIAS COMO UNITY, MATLAB, HTML, CSS E JAVASCRIPT.'
    }
}

export const projects = {
    'projectDesc-1': {
        'en': 'CHEEMS IS A PROGRAMMING LANGUAGE STILL UNDER CONSTRUCTION AND WRITTEN IN JAVASCRIPT. JUST FOR THE MEMES, IT IS A MEMELANG.',
        'es': 'CHEEMS ES UN LENGUAJE DE PROGRAMACIÓN AÚN EN CONSTRUCCIÓN Y ESCRITO EN JAVASCRIPT. SOLO PARA LOS MEMES, ES UN MEMELANG.',
        'pt': 'CHEEMS É UMA LINGUAGEM DE PROGRAMAÇÃO AINDA EM CONSTRUÇÃO E ESCRITO EM JAVASCRIPT. SOMENTE PARA MEMES, É UM MEMELANG.'
    },
    'projectDesc-2': {
        'en': 'DUOLINGO KILLER IS AN AUTOMATION WORK CREATED TO BEAT DUOLINGO. WRITTEN IN PYTHON, USING SELENIUM AND THE PAGE OBJECT MODEL DESIGN PATTERN.',
        'es': 'DUOLINGO KILLER ES UN TRABAJO DE AUTOMATIZACIÓN CREADO PARA VENCER A DUOLINGO. ESCRITO EN PYTHON, UTILIZANDO SELENIUM Y EL PATRÓN DE DISEÑO PAGE OBJECT MODEL.',
        'pt': 'DUOLINGO KILLER É UM TRABALHO DE AUTOMAÇÃO CRIADO PARA VENCER DUOLINGO. ESCRITO EM PYTHON, UTILIZANDO SELENIUM E O PADRÃO DE PROJETO DO PAGE OBJECT MODEL.'
    },
    'projectDesc-3': {
        'en': 'A SET OF IMAGE PROCESSING ALGORITHMS WRITTEN IN PURE JAVASCRIPT, THESE ALGORITHMS ARE MEANT TO RUN ON WEB BROWSER SINCE WEB CANVAS IS IMPLEMENTED.',
        'es': 'UN CONJUNTO DE ALGORITMOS DE PROCESAMIENTO DE IMÁGENES ESCRITOS EN JAVASCRIPT PURO, ESTOS ALGORITMOS ESTÁN PENSADOS PARA EJECUTARSE EN EL NAVEGADOR WEB PORQUE QUE SE IMPLEMENTA EL WEB CANVAS.',
        'pt': 'UM CONJUNTO DE ALGORITMOS DE PROCESSAMENTO DE IMAGEM ESCRITOS EM JAVASCRIPT PURO, ESTES ALGORITMOS DESTINAM-SE A SER EXECUTADOS NO NAVEGADOR DA WEB PORQUE A WEB CANVAS ESTÁ IMPLEMENTADA.'
    }
}

export const contact = {
    'contactMail': {
        'en': 'MAIL',
        'es': 'CORREO',
        'pt': 'CORRESPONDÊNCIA'
    },
    'contactMailContent': {
        'en': 'HEISRAMBY[AT]GMAIL.COM',
        'es': 'HEISRAMBY[AT]GMAIL.COM',
        'pt': 'HEISRAMBY[AT]GMAIL.COM'
    },
    'contactGitHub': {
        'en': 'GITHUB',
        'es': 'GITHUB',
        'pt': 'GITHUB'
    },
    'contactGitHubContent': {
        'en': 'MEMBURG',
        'es': 'MEMBURG',
        'pt': 'MEMBURG'
    },
    'contactGitLab': {
        'en': 'GITLAB',
        'es': 'GITLAB',
        'pt': 'GITHUB'
    },
    'contactGitLabContent': {
        'en': 'MEMBURG',
        'es': 'MEMBURG',
        'pt': 'MEMBURG'
    },
    'contactLinkedIn': {
        'en': 'LINKEDIN',
        'es': 'LINKEDIN',
        'pt': 'LINKEDIN'
    },
    'contactLinkedInContent': {
        'en': 'MEMBURG',
        'es': 'MEMBURG',
        'pt': 'MEMBURG'
    },
    'contactTwitter': {
        'en': 'TWITTER',
        'es': 'TWITTER',
        'pt': 'TWITTER'
    },
    'contactTwitterContent': {
        'en': '[AT]MEMBURG',
        'es': '[AT]MEMBURG',
        'pt': '[AT]MEMBURG'
    }
}

export const multilangMonths = {
    'en': ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'],
    'es': ['ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AGO', 'SEP', 'OCT', 'NOV', 'DIC'],
    'pt': ['JAN', 'FEV', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AUG', 'SET', 'OUT', 'NOV', 'DEZ']
}